name: Build Cosmetic Shop APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Recuperer le projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer Buildozer et Cython
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.36

      - name: Installer Android SDK et accepter les licences
        run: |
          export ANDROID_HOME="$HOME/.buildozer/android/platform/android-sdk"
          export ANDROID_SDK_ROOT="$ANDROID_HOME"

          mkdir -p "$ANDROID_HOME/licenses"

          yes | sdkmanager --licenses || true

          sdkmanager "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

      - name: Construire APK
        run: |
          yes | buildozer android debug

      - name: Chercher les APK
        run: |
          echo "===================================="
          echo "RECHERCHE DES APK"
          echo "===================================="

          find . -type f -name "*.apk" -print

          echo "===================================="
          echo "CONTENU DE BIN"
          echo "===================================="

          if [ -d "bin" ]; then
            ls -lah bin
          else
            echo "Le dossier bin n'existe pas."
          fi

      - name: Recuperer APK
        uses: actions/upload-artifact@v4
        with:
          name: cosmetic-shop-apk
          path: |
            **/*.apk
          if-no-files-found: error
