name: Build Cosmetic Shop APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Recuperer le projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.36

      - name: Installer les dependances systeme
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libffi-dev \
            libssl-dev

      - name: Construire APK
        run: |
          buildozer android debug

      - name: Rechercher les APK
        run: |
          echo "========================================"
          echo "RECHERCHE DES FICHIERS APK"
          echo "========================================"

          find . -type f -name "*.apk" -print

          echo "========================================"
          echo "CONTENU DU DOSSIER BIN"
          echo "========================================"

          if [ -d "bin" ]; then
            ls -lah bin
          else
            echo "Le dossier bin n'existe pas."
          fi

      - name: Recuperer APK
        uses: actions/upload-artifact@v4
        with:
          name: cosmetic-shop-apk
          path: |
            **/*.apk
          if-no-files-found: error
